---
kind: pkgfile.Build
spec:
  targets:
    - install-cni
    - talosctl-cni-bundle-install
  reproducibleTargetName: reproducibility
---
kind: common.Renovate
spec:
  customManagers:
    - customType: regex
      fileMatch:
        - Pkgfile
      matchStrings:
        - '# renovate: datasource=(?<datasource>.*?)(?:\s+extractVersion=(?<extractVersion>.+?))?(?:\s+versioning=(?<versioning>.+?))?\s+depName=(?<depName>.+?)?\s(?:\s+.*_(?:version|VERSION):\s+(?<currentValue>.*))?(?:\s.*_(?:ref|REF):\s+(?<currentDigest>.*))?'
      versioningTemplate: "{{#if versioning}}{{versioning}}{{else}}semver{{/if}}"
    - customType: regex
      fileMatch:
        - Pkgfile
        - Makefile
      matchStrings:
        - ghcr.io\/siderolabs\/bldr:(?<currentValue>v.*)
      depNameTemplate: siderolabs/bldr
      datasourceTemplate: github-tags
      versioningTemplate: semver
